### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by Wecros** [ScriptaGames/zorbio#558]
Hello, when I try to play the game for WARHW at http://zorbio.openshiftdemos.com/, the game is stuck at loading. No matter how much time I wait (10+ mins).

Is that a problem with the server or the game (too big)? Here is the screenshot.

![Screenshot from 2020-10-26 21-17-32](https://user-images.githubusercontent.com/33804903/97223891-b0190c00-17d0-11eb-98a8-19b3c2468cf4.png)

Thanks for resolving the issue / telling me it has nothing to do with development :D (Don't know who else to contact)

**Comment by mwcz** [comment]
Hey @Wecros, thanks for the bug report.  It would be helpful to see if there are any errors in the browser console.  The Zorbio instance for WARHW is gone, but you can try to play at https://zorb.io and let us know if you have the problem there too.  If you do, seeing any console errors would be great.  Thanks!

**Comment by Wecros** [comment]
[zorb.io-1604575544515.log](https://github.com/ScriptaGames/zorbio/files/5494011/zorb.io-1604575544515.log)

Here is the log from the console.

**Comment by mwcz** [comment]
Ahh, I think the region picker is trying to point you at a server that doesn't exist anymore.  @Jared-Sprague what do you think?

**Comment by Jared-Sprague** [comment]
@Wecros This should be fixed now that Zorbio has moved to it's permanent home at OpenShift dedicated @ https://zorb.io

Let us know if you have any problems loading again! Thanks for the report! Closing for now.

**Comment by Wecros** [comment]
Confirming that it has been fixed, fun game :)
